### PR TITLE
Updated to spconv==1.1

### PR DESCRIPTION
**Pull request by codyreading**
- Updated `dataset.py` and `kitti_dataset.py` to use `VoxelGeneratorV2`
- Updated `requirements.txt` and `setup.py` to specify `spconv==1.1`
- Tested PointPillars with results:
```
Car AP@0.70, 0.70, 0.70:
bbox AP:90.7802, 89.5710, 88.1988
bev  AP:90.0862, 87.3121, 83.9497
3d   AP:87.3674, 77.2977, 74.0227
aos  AP:90.75, 89.37, 87.89
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:95.9010, 92.0908, 90.7773
bev  AP:94.1856, 88.3521, 85.4229
3d   AP:88.3821, 78.4251, 74.9309
aos  AP:95.87, 91.86, 90.43
Car AP@0.70, 0.50, 0.50:
bbox AP:90.7802, 89.5710, 88.1988
bev  AP:95.3721, 90.0208, 89.1257
3d   AP:95.3044, 89.9037, 88.8997
aos  AP:90.75, 89.37, 87.89
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:95.9010, 92.0908, 90.7773
bev  AP:97.2666, 94.5944, 93.5978
3d   AP:97.2260, 94.2424, 92.9334
aos  AP:95.87, 91.86, 90.43
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:60.3184, 57.2768, 54.1461
bev  AP:55.1695, 50.0249, 46.1048
3d   AP:50.5018, 45.4544, 41.0912
aos  AP:42.50, 40.33, 37.97
Pedestrian AP_R40@0.50, 0.50, 0.50:
bbox AP:60.1178, 56.4277, 53.1250
bev  AP:54.5183, 48.7809, 44.7121
3d   AP:49.0521, 43.7786, 39.1144
aos  AP:39.67, 36.77, 34.45
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:60.3184, 57.2768, 54.1461
bev  AP:66.3091, 63.0741, 59.7845
3d   AP:66.2020, 62.4316, 59.2472
aos  AP:42.50, 40.33, 37.97
Pedestrian AP_R40@0.50, 0.25, 0.25:
bbox AP:60.1178, 56.4277, 53.1250
bev  AP:66.7191, 62.8219, 59.4442
3d   AP:66.3862, 62.2832, 58.9252
aos  AP:39.67, 36.77, 34.45
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:84.5649, 71.6686, 68.0017
bev  AP:81.5557, 64.4501, 61.8452
3d   AP:79.1085, 62.6828, 59.1882
aos  AP:84.28, 69.90, 66.25
Cyclist AP_R40@0.50, 0.50, 0.50:
bbox AP:87.6933, 72.7717, 68.6119
bev  AP:83.3776, 65.4307, 61.4462
3d   AP:80.3914, 62.6057, 58.7745
aos  AP:87.36, 70.83, 66.62
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:84.5649, 71.6686, 68.0017
bev  AP:83.6275, 69.9468, 65.7707
3d   AP:83.6275, 69.8436, 65.7707
aos  AP:84.28, 69.90, 66.25
Cyclist AP_R40@0.50, 0.25, 0.25:
bbox AP:87.6933, 72.7717, 68.6119
bev  AP:86.7431, 70.6220, 66.3741
3d   AP:86.7431, 70.5932, 66.3730
aos  AP:87.36, 70.83, 66.62
```

### CODE REVIEW

**Comment by sshaoshuai** [comment]
Hi, 
How about the memory cost and speed of spconv1.1?  Could you run PartA2 with batch_size=4 on spconv1.1? 
I  think the best way maybe we support spconv1.1 in a separte branch, or add a try---except strategy, which try to import spconv 1.0 first, if it fails, then we use the spconv 1.1.

**Comment by codyreading** [comment]
Hi Shaoshuai,
Sure, I'll get these results shortly and update it here. I believe the underlying code is the same, its just the interface has changed. 

I'll look into the try-except strategy for the library.

**Comment by codyreading** [comment]
Hi Shaoshuai,

I've listed the results for running PartA2_fc with batch_size=4. These are the results for the testing script:

spconv-1.0:
Time: 04:28
Speed: 3.52it/s
Memory: 1800 MiB per process
GPU Memory: 4603MiB

spconv-1.1:
Time: 04:32
Speed: 3.47 it/s
Memory: 1800 MiB per process
GPU Memory: 7323 MiB

The time is about the same, but 1.1 uses a lot more GPU memory. This was not in the VoxelGeneration, but rather in the RPN in the `UNetV2` module specifically in the SparseConvolution layers. I guess the updated implementation consumes a lot more memory.

Additionally, I also created results for just the voxel generator process. I generate voxel grids for each sample in the dataset and have the average time and amount of memory used.
spconv-1.0:
VoxelGenTime (Avg): 1.60195 ms
VoxelGenMemory (Avg): 0.773 MiB

spconv-1.1:
VoxelGenTime (Avg):  2.296293 ms
VoxelGenMemory (Avg): 1.629 MiB

1.1 is slower and consumes more memory, which I believe are due to the additional outputs.\

Should I continue with adding support for spconv-1.1?

**Comment by sshaoshuai** [comment]
Hi, 
Thank you so much for the detailed comparison between spconv 1.0 and 1.1. 
I think we'd better use the spconv 1.0 as default setting based on your results, otherwise there may be some problems on training with larger batch size with spconv 1.1, as mentioned in https://github.com/sshaoshuai/PCDet/issues/3 .

**Comment by codyreading** [comment]
Okay sounds good, I'll make the changes accordingly

**Comment by codyreading** [comment]
Hi Shaoshuai,

I updated to use a try except block, to try spconv 1.0 first using the `VoxelGenerator` class, and if that fails then use the `VoxelGeneratorV2` class. The results for both version are unchanged and shown here:.

Final results with  PartA2_fc with batch_size=4

**spconv==1.0**
Time: 04:28
Speed: 3.52it/s
Memory: 1800 MiB per process
GPU Memory: 4603MiB
Car AP@0.70, 0.70, 0.70:
bbox AP:95.9472, 89.4109, 89.0477
bev  AP:90.3133, 87.9198, 87.1329
3d   AP:89.5733, 79.3109, 78.6109
aos  AP:95.92, 89.32, 88.89
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:97.7560, 93.5203, 91.8514
bev  AP:94.8597, 88.7092, 88.3704
3d   AP:92.2765, 82.7087, 80.3474
aos  AP:97.73, 93.40, 91.67
Car AP@0.70, 0.50, 0.50:
bbox AP:95.9472, 89.4109, 89.0477
bev  AP:95.9159, 89.4239, 89.1479
3d   AP:95.8768, 89.3766, 89.0859
aos  AP:95.92, 89.32, 88.89
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:97.7560, 93.5203, 91.8514
bev  AP:97.7733, 94.1463, 93.9561
3d   AP:97.7478, 94.0576, 93.6586
aos  AP:97.73, 93.40, 91.67
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:70.4074, 66.6118, 63.6454
bev  AP:65.8017, 58.7737, 55.3849
3d   AP:62.8704, 56.3679, 50.1842
aos  AP:67.40, 63.20, 59.89
Pedestrian AP_R40@0.50, 0.50, 0.50:
bbox AP:71.9298, 67.1635, 63.3396
bev  AP:65.9651, 58.9386, 54.0707
3d   AP:62.8005, 55.4155, 49.6507
aos  AP:68.65, 63.43, 59.20
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:70.4074, 66.6118, 63.6454
bev  AP:75.5496, 71.6119, 67.1354
3d   AP:75.5882, 71.5979, 67.1078
aos  AP:67.40, 63.20, 59.89
Pedestrian AP_R40@0.50, 0.25, 0.25:
bbox AP:71.9298, 67.1635, 63.3396
bev  AP:76.7197, 72.1397, 68.3084
3d   AP:76.7276, 72.1262, 68.2227
aos  AP:68.65, 63.43, 59.20
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:94.7727, 79.8316, 75.5923
bev  AP:87.5632, 73.1611, 70.4954
3d   AP:86.9893, 71.3273, 68.3141
aos  AP:94.65, 79.56, 75.36
Cyclist AP_R40@0.50, 0.50, 0.50:
bbox AP:96.0283, 80.8651, 77.8173
bev  AP:92.4056, 75.1513, 70.8643
3d   AP:91.8053, 71.5621, 68.1065
aos  AP:95.89, 80.59, 77.52
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:94.7727, 79.8316, 75.5923
bev  AP:93.4958, 77.2399, 72.6263
3d   AP:93.4958, 77.2399, 72.6263
aos  AP:94.65, 79.56, 75.36
Cyclist AP_R40@0.50, 0.25, 0.25:
bbox AP:96.0283, 80.8651, 77.8173
bev  AP:94.5466, 78.6861, 74.7379
3d   AP:94.5466, 78.6861, 74.7379
aos  AP:95.89, 80.59, 77.52

**spconv==1.1**
```
Time: 04:32
Speed: 3.47 it/s
Memory: 1800 MiB per process
GPU Memory: 7323 MiB

Car AP@0.70, 0.70, 0.70:
bbox AP:95.9472, 89.4109, 89.0477
bev  AP:90.3133, 87.9198, 87.1329
3d   AP:89.5733, 79.3109, 78.6109
aos  AP:95.92, 89.32, 88.89
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:97.7560, 93.5203, 91.8514
bev  AP:94.8597, 88.7092, 88.3704
3d   AP:92.2765, 82.7087, 80.3474
aos  AP:97.73, 93.40, 91.67
Car AP@0.70, 0.50, 0.50:
bbox AP:95.9472, 89.4109, 89.0477
bev  AP:95.9159, 89.4239, 89.1479
3d   AP:95.8768, 89.3766, 89.0859
aos  AP:95.92, 89.32, 88.89
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:97.7560, 93.5203, 91.8514
bev  AP:97.7733, 94.1463, 93.9561
3d   AP:97.7478, 94.0576, 93.6586
aos  AP:97.73, 93.40, 91.67
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:70.4074, 66.6118, 63.6454
bev  AP:65.8017, 58.7737, 55.3849
3d   AP:62.8704, 56.3679, 50.1842
aos  AP:67.40, 63.20, 59.89
Pedestrian AP_R40@0.50, 0.50, 0.50:
bbox AP:71.9298, 67.1635, 63.3396
bev  AP:65.9651, 58.9386, 54.0707
3d   AP:62.8005, 55.4155, 49.6507
aos  AP:68.65, 63.43, 59.20
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:70.4074, 66.6118, 63.6454
bev  AP:75.5496, 71.6119, 67.1354
3d   AP:75.5882, 71.5979, 67.1078
aos  AP:67.40, 63.20, 59.89
Pedestrian AP_R40@0.50, 0.25, 0.25:
bbox AP:71.9298, 67.1635, 63.3396
bev  AP:76.7197, 72.1397, 68.3084
3d   AP:76.7276, 72.1262, 68.2227
aos  AP:68.65, 63.43, 59.20
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:94.7727, 79.8316, 75.5923
bev  AP:87.5632, 73.1611, 70.4954
3d   AP:86.9893, 71.3273, 68.3141
aos  AP:94.65, 79.56, 75.36
Cyclist AP_R40@0.50, 0.50, 0.50:
bbox AP:96.0283, 80.8651, 77.8173
bev  AP:92.4056, 75.1513, 70.8643
3d   AP:91.8053, 71.5621, 68.1065
aos  AP:95.89, 80.59, 77.52
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:94.7727, 79.8316, 75.5923
bev  AP:93.4958, 77.2399, 72.6263
3d   AP:93.4958, 77.2399, 72.6263
aos  AP:94.65, 79.56, 75.36
Cyclist AP_R40@0.50, 0.25, 0.25:
bbox AP:96.0283, 80.8651, 77.8173
bev  AP:94.5466, 78.6861, 74.7379
3d   AP:94.5466, 78.6861, 74.7379
aos  AP:95.89, 80.59, 77.52
```

**Comment by sshaoshuai** [comment]
Hi , 
Thanks for the contribution, I have merged it into the master branch.

**Pull request merged**
